language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'

script:
  - npm run test
  - codecov

after_success:
  - npm run semantic-release